const productBtn = document.querySelectorAll('.products-link')
const productModal = document.querySelector('[data-modal=products]')
const modalImage = productModal.querySelector('.product-modal-image')
const productsListItem = document.querySelectorAll('.product-modal-stats-item')
const productsListItemValue = document.querySelectorAll('.product-modal-stats-item-value')
